"""
Listing Summary Model

Stores property-level chat summaries generated by the AI.
One summary per listing, updated periodically.
"""
import uuid
from datetime import datetime
from sqlalchemy import Column, Text, DateTime, ForeignKey, UniqueConstraint, Index
from sqlalchemy.dialects.postgresql import UUID, JSONB
from app.db.base import Base


class ListingSummary(Base):
    """
    Stores property-level chat summaries generated by the AI.
    One summary per listing, updated periodically.
    """
    __tablename__ = "listing_summaries"

    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )

    listing_id = Column(
        "listing_id",
        UUID(as_uuid=True),
        nullable=False,
        unique=True,
        index=True,
    )

    summary = Column(
        Text,
        nullable=True,
        comment="Natural language summary of common user queries and themes for the listing."
    )

    last_summarised_at = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="Timestamp when summary was last generated."
    )

    created_at = Column(
        DateTime(timezone=True),
        default=datetime.utcnow,
        nullable=False,
    )

    updated_at = Column(
        DateTime(timezone=True),
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
        nullable=False,
    )

    __table_args__ = (
        UniqueConstraint("listing_id", name="uq_listing_summary_listing_id"),
        Index("idx_listing_summary_last_summarised_at", "last_summarised_at"),
        Index("idx_listing_summary_updated_at", "updated_at"),
    )
